name: BAD DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Vulnerability scan
        run: pip install pip-audit && pip-audit

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bad-app .

  container-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Scan image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: bad-app

  deploy:
    runs-on: ubuntu-latest
    needs: container-scan
    steps:
      - name: Deploy
        run: echo "Deployment attempted"
